### ISSUE TITLE
empty config file

### ISSUE THREAD

**Issue by wangzeng2001** [akiomiyao/tef#1]
Dear Miyao,
Sorry to bother you, I'm trying to learn your pipeline of tef, I put the file in the specified directory, */tef-main/plau/read/*.1.fq.gz, */tef-main/plau/read/*.2.fq.gz, */tef-main/plag/read/*.1.fq.gz, */tef-main/plag/read/*.1.fq.gz,*/tef-main/P_wil/P_wil.fasta.gz . And I run the command "perl tef.pl a=plau,b=plag,ref=P_wil,option=clear,max_process=8,sort_tmp=teftmp". However,I get the empty file of config file. 
Best wishes,
Zeng Wang

**Comment by akiomiyao** [comment]
Hi Zeng,

To make the config file manually, write name of chromosomes in the sequence of appearance of fasta file. If the entry of chromosome is not required, NOP shold be specified.
For example, in the case of Drosophila melanogaster,

zcat dmel-all-chromosome-r6.26.fasta.gz |grep '>'
>2L type=golden_path_region; loc=2L:1..23513712; ID=2L; dbxref=GB:AE014134,GB:AE014134,REFSEQ:NT_033779; MD5=b6a98b7c676bdaa11ec9521ed15aff2b; length=23513712; release=r6.26; species=Dmel;
>2R type=golden_path_region; loc=2R:1..25286936; ID=2R; dbxref=GB:AE013599,GB:AE013599,REFSEQ:NT_033778; MD5=2ecce4ca1c0106bb7c63a78b93ab49ba; length=25286936; release=r6.26; species=Dmel;
>3L type=golden_path_region; loc=3L:1..28110227; ID=3L; dbxref=GB:AE014296,GB:AE014296,REFSEQ:NT_037436; MD5=3c3ea06b22af8cc59809dbf8d154791e; length=28110227; release=r6.26; species=Dmel;
>3R type=golden_path_region; loc=3R:1..32079331; ID=3R; dbxref=GB:AE014297,GB:AE014297,REFSEQ:NT_033777; MD5=420540d26d86fbf14185d2f2d68af9c4; length=32079331; release=r6.26; species=Dmel;
>4 type=golden_path_region; loc=4:1..1348131; ID=4; dbxref=GB:AE014135,GB:AE014135,REFSEQ:NC_004353; MD5=8dbdf26f38049dd9df4076b6d480ae61; length=1348131; release=r6.26; species=Dmel;
>X type=golden_path_region; loc=X:1..23542271; ID=X; dbxref=GB:AE014298,GB:AE014298,REFSEQ:NC_004354; MD5=f7228bbf9f8fa0af457bc2fb7e396e4d; length=23542271; release=r6.26; species=Dmel;
>Y type=golden_path_region; loc=Y:1..3667352; ID=Y; dbxref=GB:CP007106,GB:CP007106,REFSEQ:NC_024512; MD5=0938dd2253a423799e7938dc892f1c04; length=3667352; release=r6.26; species=Dmel;
>2Cen_mapped_Scaffold_10_D1684 type=golden_path_region; loc=2Cen_mapped_Scaffold_10_D1684:1..19956; ID=2Cen_mapped_Scaffold_10_D1684; dbxref=GB:CP007071,GB:CP007071,REFSEQ:NW_007931073; MD5=b71b59981d0bc7d367792f99638e8ff5; length=19956; release=r6.26; species=Dmel;
>2Cen_mapped_Scaffold_43_D1668 type=golden_path_region; loc=2Cen_mapped_Scaffold_43_D1668:1..44411; ID=2Cen_mapped_Scaffold_43_D1668; dbxref=GB:CP007072,GB:CP007072,REFSEQ:NW_007931074; MD5=8f5e867a2b263eb401acf5a10a1a8f19; length=44411; release=r6.26; species=Dmel;

The config file is
2L
2R
3L
3R
4
X
Y
NOP
continue NOP

Cheers,

Akio
